# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMFciutKwg_po7QygZtP60u3u4d6pA5p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('IRIS.csv')
df

df.head(10)

df.tail(10)

df.shape

df.size

df.columns

df.dtypes

df.describe()

df.isnull().sum()

df.duplicated().sum()

df  = df.drop_duplicates()

df.empty

df.dropna()

X = df.iloc[:, :-1]
Y = df.iloc[:, -1]

if Y.dtype == 'object':
    le = LabelEncoder()
    Y = le.fit_transform(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model = SVC(kernel='linear')

model.fit(X_train, Y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(Y_test, y_pred))
print("Classification Report:\n", classification_report(Y_test, y_pred))

sns.pairplot(df, hue='species', markers=["o", "s", "D"])
plt.show()

df.plot(kind='box', subplots=True, layout=(2,2), sharex=False, sharey=False)
plt.show()

df.hist()
plt.show()